"""create historical evidence core

Revision ID: a8dca2b9df60
Revises:
Create Date: 2026-07-25 23:31:00.450555
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "a8dca2b9df60"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "entities",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "entity_type",
            sa.Enum(
                "person",
                "organization",
                "public_office",
                "mandate",
                "electoral_territory",
                "judicial_case",
                "judicial_event",
                name="entity_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_entities")),
    )
    op.create_table(
        "ingestion_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_key", sa.String(length=120), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "running",
                "completed",
                "partial",
                "failed",
                name="ingestion_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("records_created", sa.Integer(), nullable=False),
        sa.Column("records_updated", sa.Integer(), nullable=False),
        sa.Column("records_skipped", sa.Integer(), nullable=False),
        sa.Column("records_failed", sa.Integer(), nullable=False),
        sa.Column("error_summary", sa.Text(), nullable=True),
        sa.Column(
            "metadata",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.CheckConstraint(
            "records_created >= 0",
            name=op.f("ck_ingestion_runs_records_created_nonnegative"),
        ),
        sa.CheckConstraint(
            "records_failed >= 0",
            name=op.f("ck_ingestion_runs_records_failed_nonnegative"),
        ),
        sa.CheckConstraint(
            "records_skipped >= 0",
            name=op.f("ck_ingestion_runs_records_skipped_nonnegative"),
        ),
        sa.CheckConstraint(
            "records_updated >= 0",
            name=op.f("ck_ingestion_runs_records_updated_nonnegative"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingestion_runs")),
    )
    op.create_table(
        "source_documents",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_key", sa.String(length=120), nullable=False),
        sa.Column(
            "source_type",
            sa.Enum(
                "official_document",
                "administrative_resolution",
                "judicial_filing",
                "judicial_decision",
                "final_judicial_decision",
                "legislative_record",
                "public_registry",
                "transparency_response",
                "archive_document",
                "media_reference",
                "other",
                name="source_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("original_url", sa.Text(), nullable=True),
        sa.Column("issuing_body", sa.Text(), nullable=True),
        sa.Column("publication_date", sa.Date(), nullable=True),
        sa.Column("document_date", sa.Date(), nullable=True),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("storage_path", sa.Text(), nullable=True),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("mime_type", sa.String(length=255), nullable=True),
        sa.Column("language", sa.String(length=20), nullable=True),
        sa.Column(
            "access_status",
            sa.Enum(
                "available",
                "restricted",
                "unavailable",
                "unknown",
                name="access_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("parent_document_id", sa.Uuid(), nullable=True),
        sa.Column("supersedes_document_id", sa.Uuid(), nullable=True),
        sa.Column(
            "metadata",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "length(sha256) = 64",
            name=op.f("ck_source_documents_source_document_sha256_length"),
        ),
        sa.ForeignKeyConstraint(
            ["parent_document_id"],
            ["source_documents.id"],
            name=op.f("fk_source_documents_parent_document_id_source_documents"),
        ),
        sa.ForeignKeyConstraint(
            ["supersedes_document_id"],
            ["source_documents.id"],
            name=op.f("fk_source_documents_supersedes_document_id_source_documents"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_documents")),
        sa.UniqueConstraint(
            "source_key",
            "sha256",
            "retrieved_at",
            name="uq_source_document_provenance_version",
        ),
    )
    op.create_index(
        "ix_source_documents_source_key",
        "source_documents",
        ["source_key"],
        unique=False,
    )
    op.create_table(
        "source_snapshots",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_key", sa.String(length=120), nullable=False),
        sa.Column("operation", sa.Text(), nullable=True),
        sa.Column(
            "parameters",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=True,
        ),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("http_status", sa.Integer(), nullable=True),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("storage_path", sa.Text(), nullable=False),
        sa.Column(
            "processing_status",
            sa.Enum(
                "downloaded",
                "parsed",
                "partially_parsed",
                "failed",
                "superseded",
                name="processing_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("error_summary", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "length(sha256) = 64",
            name=op.f("ck_source_snapshots_snapshot_sha256_length"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_snapshots")),
        sa.UniqueConstraint(
            "source_key",
            "sha256",
            "retrieved_at",
            name="uq_source_snapshot_provenance_version",
        ),
    )
    op.create_table(
        "electoral_territories",
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column(
            "territory_type",
            sa.Enum(
                "district",
                "senatorial_constituency",
                "region",
                "commune",
                "national",
                "other",
                name="territory_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("number", sa.String(length=40), nullable=True),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("valid_from", sa.Date(), nullable=True),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.Column("source_document_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["entity_id"],
            ["entities.id"],
            name=op.f("fk_electoral_territories_entity_id_entities"),
        ),
        sa.ForeignKeyConstraint(
            ["source_document_id"],
            ["source_documents.id"],
            name=op.f("fk_electoral_territories_source_document_id_source_documents"),
        ),
        sa.PrimaryKeyConstraint("entity_id", name=op.f("pk_electoral_territories")),
    )
    op.create_table(
        "evidence_claims",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("subject_entity_id", sa.Uuid(), nullable=False),
        sa.Column(
            "predicate",
            sa.Enum(
                "HELD_OFFICE",
                "MEMBER_OF_PARTY",
                "MEMBER_OF_ORGANIZATION",
                "SHAREHOLDER_OF",
                "DIRECTOR_OF",
                "PARTNER_OF",
                "PARTICIPATED_IN_CASE",
                "ACCUSED_IN",
                "CONVICTED_IN",
                "ACQUITTED_IN",
                "DISMISSED_FROM_CASE",
                "SANCTIONED_BY",
                "SERVED_WITH",
                "CO_DEFENDANT_WITH",
                "CO_OWNED_WITH",
                name="evidence_predicate",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("object_entity_id", sa.Uuid(), nullable=True),
        sa.Column(
            "literal_value",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=True,
        ),
        sa.Column("valid_from", sa.Date(), nullable=True),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.Column(
            "evidence_level",
            sa.Enum(
                "unverified_reference",
                "media_reference",
                "official_document",
                "administrative_resolution",
                "judicial_filing",
                "judicial_decision",
                "final_judicial_decision",
                name="evidence_level",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("source_document_id", sa.Uuid(), nullable=False),
        sa.Column("source_excerpt", sa.Text(), nullable=False),
        sa.Column("source_location", sa.Text(), nullable=True),
        sa.Column("technical_confidence", sa.Float(), nullable=True),
        sa.Column(
            "review_status",
            sa.Enum(
                "discovered",
                "extracted",
                "pending_review",
                "verified",
                "rejected",
                "corrected",
                "archived",
                name="claim_review_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "publication_status",
            sa.Enum(
                "private",
                "review_only",
                "publishable",
                "published",
                "withdrawn",
                name="publication_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("corrected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("supersedes_claim_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(object_entity_id IS NOT NULL AND literal_value IS NULL) OR "
            "(object_entity_id IS NULL AND literal_value IS NOT NULL)",
            name=op.f("ck_evidence_claims_claim_exactly_one_object"),
        ),
        sa.CheckConstraint(
            "technical_confidence IS NULL OR "
            "(technical_confidence >= 0 AND technical_confidence <= 1)",
            name=op.f("ck_evidence_claims_claim_confidence_range"),
        ),
        sa.CheckConstraint(
            "valid_to IS NULL OR valid_from IS NULL OR valid_to >= valid_from",
            name=op.f("ck_evidence_claims_claim_valid_dates"),
        ),
        sa.ForeignKeyConstraint(
            ["object_entity_id"],
            ["entities.id"],
            name=op.f("fk_evidence_claims_object_entity_id_entities"),
        ),
        sa.ForeignKeyConstraint(
            ["source_document_id"],
            ["source_documents.id"],
            name=op.f("fk_evidence_claims_source_document_id_source_documents"),
        ),
        sa.ForeignKeyConstraint(
            ["subject_entity_id"],
            ["entities.id"],
            name=op.f("fk_evidence_claims_subject_entity_id_entities"),
        ),
        sa.ForeignKeyConstraint(
            ["supersedes_claim_id"],
            ["evidence_claims.id"],
            name=op.f("fk_evidence_claims_supersedes_claim_id_evidence_claims"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evidence_claims")),
    )
    op.create_index(
        "ix_evidence_claims_object",
        "evidence_claims",
        ["object_entity_id"],
        unique=False,
    )
    op.create_index(
        "ix_evidence_claims_subject_predicate",
        "evidence_claims",
        ["subject_entity_id", "predicate"],
        unique=False,
    )
    op.create_table(
        "judicial_cases",
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("case_identifier", sa.String(length=255), nullable=False),
        sa.Column("court_name", sa.Text(), nullable=False),
        sa.Column("jurisdiction", sa.Text(), nullable=True),
        sa.Column("case_type", sa.Text(), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column(
            "current_status",
            sa.Enum(
                "reported",
                "filed",
                "investigating",
                "charged",
                "trial",
                "decided",
                "closed",
                "unknown",
                name="case_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("result_summary", sa.Text(), nullable=True),
        sa.Column(
            "finality_status",
            sa.Enum(
                "not_applicable",
                "pending",
                "appealable",
                "final",
                "revoked",
                "unknown",
                name="case_finality_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("source_document_id", sa.Uuid(), nullable=False),
        sa.Column(
            "review_status",
            sa.Enum(
                "discovered",
                "extracted",
                "pending_review",
                "verified",
                "rejected",
                "corrected",
                "archived",
                name="case_review_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["entity_id"],
            ["entities.id"],
            name=op.f("fk_judicial_cases_entity_id_entities"),
        ),
        sa.ForeignKeyConstraint(
            ["source_document_id"],
            ["source_documents.id"],
            name=op.f("fk_judicial_cases_source_document_id_source_documents"),
        ),
        sa.PrimaryKeyConstraint("entity_id", name=op.f("pk_judicial_cases")),
        sa.UniqueConstraint(
            "court_name", "case_identifier", name="uq_judicial_case_court_identifier"
        ),
    )
    op.create_table(
        "organizations",
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column(
            "organization_type",
            sa.Enum(
                "political_party",
                "coalition",
                "company",
                "foundation",
                "public_body",
                "association",
                "other",
                name="organization_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("canonical_name", sa.Text(), nullable=False),
        sa.Column("original_name", sa.Text(), nullable=True),
        sa.Column("valid_from", sa.Date(), nullable=True),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(
            ["entity_id"],
            ["entities.id"],
            name=op.f("fk_organizations_entity_id_entities"),
        ),
        sa.PrimaryKeyConstraint("entity_id", name=op.f("pk_organizations")),
    )
    op.create_table(
        "persons",
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("canonical_name", sa.Text(), nullable=False),
        sa.Column("given_names", sa.Text(), nullable=True),
        sa.Column("paternal_surname", sa.Text(), nullable=True),
        sa.Column("maternal_surname", sa.Text(), nullable=True),
        sa.Column("birth_date", sa.Date(), nullable=True),
        sa.Column("death_date", sa.Date(), nullable=True),
        sa.Column("nationality", sa.String(length=120), nullable=True),
        sa.Column("biography_summary", sa.Text(), nullable=True),
        sa.Column(
            "identity_review_status",
            sa.Enum(
                "discovered",
                "extracted",
                "pending_review",
                "verified",
                "rejected",
                "corrected",
                "archived",
                name="person_identity_review_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["entity_id"], ["entities.id"], name=op.f("fk_persons_entity_id_entities")
        ),
        sa.PrimaryKeyConstraint("entity_id", name=op.f("pk_persons")),
    )
    op.create_table(
        "public_offices",
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("normalized_name", sa.Text(), nullable=False),
        sa.Column("original_name", sa.Text(), nullable=False),
        sa.Column(
            "office_level",
            sa.Enum(
                "national",
                "regional",
                "municipal",
                "party",
                "other",
                name="office_level",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("institution_name", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["entity_id"],
            ["entities.id"],
            name=op.f("fk_public_offices_entity_id_entities"),
        ),
        sa.PrimaryKeyConstraint("entity_id", name=op.f("pk_public_offices")),
    )
    op.create_table(
        "judicial_case_persons",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("judicial_case_entity_id", sa.Uuid(), nullable=False),
        sa.Column("person_entity_id", sa.Uuid(), nullable=False),
        sa.Column("original_role", sa.Text(), nullable=False),
        sa.Column(
            "normalized_role",
            sa.Enum(
                "accused",
                "defendant",
                "convicted_person",
                "acquitted_person",
                "complainant",
                "plaintiff",
                "respondent",
                "witness",
                "attorney",
                "authority",
                "mentioned",
                "other",
                "unknown",
                name="judicial_role",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("participation_start", sa.Date(), nullable=True),
        sa.Column("participation_end", sa.Date(), nullable=True),
        sa.Column(
            "outcome",
            sa.Enum(
                "pending",
                "convicted",
                "acquitted",
                "dismissed",
                "definitively_dismissed",
                "provisionally_dismissed",
                "prescribed",
                "archived",
                "revoked",
                "not_applicable",
                "unknown",
                name="judicial_outcome",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "finality_status",
            sa.Enum(
                "not_applicable",
                "pending",
                "appealable",
                "final",
                "revoked",
                "unknown",
                name="case_person_finality_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("source_document_id", sa.Uuid(), nullable=False),
        sa.Column(
            "review_status",
            sa.Enum(
                "discovered",
                "extracted",
                "pending_review",
                "verified",
                "rejected",
                "corrected",
                "archived",
                name="case_person_review_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["judicial_case_entity_id"],
            ["judicial_cases.entity_id"],
            name=op.f(
                "fk_judicial_case_persons_judicial_case_entity_id_judicial_cases"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["person_entity_id"],
            ["persons.entity_id"],
            name=op.f("fk_judicial_case_persons_person_entity_id_persons"),
        ),
        sa.ForeignKeyConstraint(
            ["source_document_id"],
            ["source_documents.id"],
            name=op.f("fk_judicial_case_persons_source_document_id_source_documents"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_judicial_case_persons")),
        sa.UniqueConstraint(
            "judicial_case_entity_id",
            "person_entity_id",
            "original_role",
            "participation_start",
            name="uq_case_person_historical_role",
        ),
    )
    op.create_index(
        "ix_case_person_person",
        "judicial_case_persons",
        ["person_entity_id"],
        unique=False,
    )
    op.create_table(
        "judicial_events",
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("judicial_case_entity_id", sa.Uuid(), nullable=False),
        sa.Column(
            "event_type",
            sa.Enum(
                "complaint",
                "filing",
                "investigation",
                "indictment",
                "formalization",
                "accusation",
                "hearing",
                "trial",
                "judgment",
                "appeal",
                "confirmation",
                "revocation",
                "dismissal",
                "closure",
                "other",
                name="judicial_event_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("event_date", sa.Date(), nullable=True),
        sa.Column("original_description", sa.Text(), nullable=False),
        sa.Column("normalized_summary", sa.Text(), nullable=True),
        sa.Column("legal_effect", sa.Text(), nullable=False),
        sa.Column("source_document_id", sa.Uuid(), nullable=False),
        sa.Column(
            "review_status",
            sa.Enum(
                "discovered",
                "extracted",
                "pending_review",
                "verified",
                "rejected",
                "corrected",
                "archived",
                name="judicial_event_review_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["entity_id"],
            ["entities.id"],
            name=op.f("fk_judicial_events_entity_id_entities"),
        ),
        sa.ForeignKeyConstraint(
            ["judicial_case_entity_id"],
            ["judicial_cases.entity_id"],
            name=op.f("fk_judicial_events_judicial_case_entity_id_judicial_cases"),
        ),
        sa.ForeignKeyConstraint(
            ["source_document_id"],
            ["source_documents.id"],
            name=op.f("fk_judicial_events_source_document_id_source_documents"),
        ),
        sa.PrimaryKeyConstraint("entity_id", name=op.f("pk_judicial_events")),
    )
    op.create_table(
        "mandates",
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("person_entity_id", sa.Uuid(), nullable=False),
        sa.Column("public_office_entity_id", sa.Uuid(), nullable=False),
        sa.Column("electoral_territory_entity_id", sa.Uuid(), nullable=True),
        sa.Column("organization_entity_id", sa.Uuid(), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("original_title", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "elected",
                "appointed",
                "acting",
                "completed",
                "resigned",
                "removed",
                "unknown",
                name="mandate_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("source_document_id", sa.Uuid(), nullable=False),
        sa.Column(
            "review_status",
            sa.Enum(
                "discovered",
                "extracted",
                "pending_review",
                "verified",
                "rejected",
                "corrected",
                "archived",
                name="mandate_review_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.CheckConstraint(
            "end_date IS NULL OR end_date >= start_date",
            name=op.f("ck_mandates_mandate_valid_dates"),
        ),
        sa.ForeignKeyConstraint(
            ["electoral_territory_entity_id"],
            ["electoral_territories.entity_id"],
            name=op.f(
                "fk_mandates_electoral_territory_entity_id_electoral_territories"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["entity_id"], ["entities.id"], name=op.f("fk_mandates_entity_id_entities")
        ),
        sa.ForeignKeyConstraint(
            ["organization_entity_id"],
            ["organizations.entity_id"],
            name=op.f("fk_mandates_organization_entity_id_organizations"),
        ),
        sa.ForeignKeyConstraint(
            ["person_entity_id"],
            ["persons.entity_id"],
            name=op.f("fk_mandates_person_entity_id_persons"),
        ),
        sa.ForeignKeyConstraint(
            ["public_office_entity_id"],
            ["public_offices.entity_id"],
            name=op.f("fk_mandates_public_office_entity_id_public_offices"),
        ),
        sa.ForeignKeyConstraint(
            ["source_document_id"],
            ["source_documents.id"],
            name=op.f("fk_mandates_source_document_id_source_documents"),
        ),
        sa.PrimaryKeyConstraint("entity_id", name=op.f("pk_mandates")),
    )
    op.create_table(
        "manual_reviews",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("claim_id", sa.Uuid(), nullable=True),
        sa.Column("person_entity_id", sa.Uuid(), nullable=True),
        sa.Column("source_document_id", sa.Uuid(), nullable=True),
        sa.Column("reviewer_identifier", sa.String(length=255), nullable=False),
        sa.Column(
            "decision",
            sa.Enum(
                "approve",
                "reject",
                "request_changes",
                "correct",
                "archive",
                name="review_decision",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "previous_status",
            sa.Enum(
                "discovered",
                "extracted",
                "pending_review",
                "verified",
                "rejected",
                "corrected",
                "archived",
                name="previous_review_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=True,
        ),
        sa.Column(
            "resulting_status",
            sa.Enum(
                "discovered",
                "extracted",
                "pending_review",
                "verified",
                "rejected",
                "corrected",
                "archived",
                name="resulting_review_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "metadata",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.CheckConstraint(
            "claim_id IS NOT NULL OR person_entity_id IS NOT NULL OR "
            "source_document_id IS NOT NULL",
            name=op.f("ck_manual_reviews_manual_review_has_target"),
        ),
        sa.CheckConstraint(
            "length(trim(reviewer_identifier)) > 0",
            name=op.f("ck_manual_reviews_manual_review_reviewer_not_empty"),
        ),
        sa.ForeignKeyConstraint(
            ["claim_id"],
            ["evidence_claims.id"],
            name=op.f("fk_manual_reviews_claim_id_evidence_claims"),
        ),
        sa.ForeignKeyConstraint(
            ["person_entity_id"],
            ["persons.entity_id"],
            name=op.f("fk_manual_reviews_person_entity_id_persons"),
        ),
        sa.ForeignKeyConstraint(
            ["source_document_id"],
            ["source_documents.id"],
            name=op.f("fk_manual_reviews_source_document_id_source_documents"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_manual_reviews")),
    )
    op.create_table(
        "person_identities",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("person_entity_id", sa.Uuid(), nullable=False),
        sa.Column("source_key", sa.String(length=120), nullable=False),
        sa.Column("source_person_id", sa.String(length=255), nullable=False),
        sa.Column("displayed_name", sa.Text(), nullable=False),
        sa.Column("valid_from", sa.Date(), nullable=True),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.Column(
            "identity_status",
            sa.Enum(
                "candidate",
                "confirmed",
                "rejected",
                "superseded",
                name="identity_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("source_document_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["person_entity_id"],
            ["persons.entity_id"],
            name=op.f("fk_person_identities_person_entity_id_persons"),
        ),
        sa.ForeignKeyConstraint(
            ["source_document_id"],
            ["source_documents.id"],
            name=op.f("fk_person_identities_source_document_id_source_documents"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_person_identities")),
        sa.UniqueConstraint(
            "source_key",
            "source_person_id",
            name="uq_person_identity_source_identifier",
        ),
    )
    op.create_index(
        "ix_person_identities_person",
        "person_identities",
        ["person_entity_id"],
        unique=False,
    )
    op.create_table(
        "political_affiliations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("person_entity_id", sa.Uuid(), nullable=False),
        sa.Column("organization_entity_id", sa.Uuid(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("original_role", sa.Text(), nullable=True),
        sa.Column("source_document_id", sa.Uuid(), nullable=False),
        sa.Column(
            "review_status",
            sa.Enum(
                "discovered",
                "extracted",
                "pending_review",
                "verified",
                "rejected",
                "corrected",
                "archived",
                name="affiliation_review_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.CheckConstraint(
            "end_date IS NULL OR start_date IS NULL OR end_date >= start_date",
            name=op.f("ck_political_affiliations_affiliation_valid_dates"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_entity_id"],
            ["organizations.entity_id"],
            name=op.f("fk_political_affiliations_organization_entity_id_organizations"),
        ),
        sa.ForeignKeyConstraint(
            ["person_entity_id"],
            ["persons.entity_id"],
            name=op.f("fk_political_affiliations_person_entity_id_persons"),
        ),
        sa.ForeignKeyConstraint(
            ["source_document_id"],
            ["source_documents.id"],
            name=op.f("fk_political_affiliations_source_document_id_source_documents"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_political_affiliations")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("political_affiliations")
    op.drop_index("ix_person_identities_person", table_name="person_identities")
    op.drop_table("person_identities")
    op.drop_table("manual_reviews")
    op.drop_table("mandates")
    op.drop_table("judicial_events")
    op.drop_index("ix_case_person_person", table_name="judicial_case_persons")
    op.drop_table("judicial_case_persons")
    op.drop_table("public_offices")
    op.drop_table("persons")
    op.drop_table("organizations")
    op.drop_table("judicial_cases")
    op.drop_index("ix_evidence_claims_subject_predicate", table_name="evidence_claims")
    op.drop_index("ix_evidence_claims_object", table_name="evidence_claims")
    op.drop_table("evidence_claims")
    op.drop_table("electoral_territories")
    op.drop_table("source_snapshots")
    op.drop_index("ix_source_documents_source_key", table_name="source_documents")
    op.drop_table("source_documents")
    op.drop_table("ingestion_runs")
    op.drop_table("entities")
    # ### end Alembic commands ###
